### ISSUE TITLE
MaxRetryExceededError when referencing a path containing undefined values

### ISSUE THREAD

**Issue by ptpt** [Netflix/falcor#853] opened 2017-07-22 10:31 UTC
```javascript
var F = require("falcor");
var Router = require("falcor-router");
var G = require("falcor-json-graph");
var Rx = require("rx");

const router = new Router([
  {
    route: 'sequenceByKey[{ranges}].imageByKey',
    get: function(pathSet) {
      return Rx.Observable.create(function(observer) {
               observer.onNext({
                 path: ["sequenceByKey", 0, "imageByKey"],
// undefined or null in the referenced path cause MaxRetryExceededError to throw
                 value: G.ref(["imageByKey", undefined]) });

               observer.onCompleted();
             });
    }
  },
]);

var model = new F.Model({"source": router});

const util = require('util');

function LOG(myObject) {
  console.log(util.inspect(myObject, {showHidden: false, depth: null}));
}

model.get([
  'sequenceByKey',
  {from: 0, to:1},
  ["imageByKey"],
  ["foo", "bar"]
]).subscribe(
  function(a) {
    LOG(a);
  },
  err => console.log(err),
  () => console.log("done")
);
```

**Comment by asyncanup** [comment] 2017-09-23 07:39
the real issue here is not `undefined`, but the fact that `imageByKey` does not have a matching route in the router. Which explains why MaxRetryExceededError would happen.

simply adding a matching route for `imageByKey` fixes the error for me and returns a valid response.
Code:
```
var F = require("falcor");
var Router = require("falcor-router");
var G = require("falcor-json-graph");
var Rx = require("rx");

const router = new Router([
  {
    route: 'sequenceByKey[{ranges}].imageByKey',
    get: function(pathSet) {
      return Rx.Observable.create(function(observer) {
               observer.onNext({
                 path: ["sequenceByKey", 0, "imageByKey"],
// undefined or null in the referenced path cause MaxRetryExceededError to throw
                 value: G.ref(["imageByKey", undefined]) });

               observer.onCompleted();
             });
    }
  },
  {
    route: 'imageByKey',
    get: function(pathSet) {
      return Rx.Observable.create(function(observer) {
               observer.onNext({
                 path: ["imageByKey"],
                 value: "hola!" });

               observer.onCompleted();
             });
    }
  },
]);

var model = new F.Model({"source": router});

const util = require('util');

function LOG(myObject) {
  console.log(util.inspect(myObject, {showHidden: false, depth: null}));
}

model.get([
  'sequenceByKey',
  {from: 0, to:1},
  ["imageByKey"],
  ["foo", "bar"]
]).subscribe(
  function(a) {
    LOG(a);
  },
  err => console.log(err),
  () => console.log("done")
);
```
Response:
```
{ json:
   { sequenceByKey:
      { '0': { '$__path': [ 'sequenceByKey', 0 ], imageByKey: 'hola!' },
        '$__path': [ 'sequenceByKey' ] } } }
```

@ptpt does that make sense?
is there another issue here that i might be missing?

**Comment by sdesai** [comment] 2017-10-04 22:48
Closing out. Feel free to re-open if you think we got the wrong root cause.

**Closed by sdesai** 2017-10-04 22:48 UTC
Labels: bug
