### ISSUE TITLE
Error with {keys:props} "pathSet.keys.forEach is not a function"

### ISSUE THREAD

**Issue by Bretto** [Netflix/falcor#480] opened 2015-08-25 07:06 UTC
Testing
```
route: 'tasksById[{keys:ids}][{keys:props}]',
pathSet.keys.forEach(function (key) {
```
error
```
pathSet.keys.forEach is not a function
```
But
```
route: 'itemById[{keys:ids}]["name","content"]',
pathSet[2].forEach(function (key) {
```
works as expected, is this a bug ?

**Comment by ewinslow** [comment] 2015-08-25 07:07
I suspect you want `pathSet.ids.forEach`?

**Comment by Bretto** [comment] 2015-08-25 08:22
No, if you have a look a the "The {keys} Pattern" section in the Router docs you will find:
```
pathSet.keys.forEach(function(key) {
    task[key] = jsong.atom(taskRecord[key]);
});
```
the keys is the breaking the ids is fine.

**Comment by dallonf** [comment] 2015-08-25 13:46
Aha, that looks like a problem in the docs. It should be `pathSet.props` at that point.

**Comment by jhusain** [comment] 2015-08-25 23:12
Confirmed.

**Comment by michaelbpaulson** [comment] 2016-02-05 16:12
@jhusain did we ever fix this ?  I am eager to close this issue :)

**Comment by jhusain** [comment] 2016-02-05 19:21
Was fixed. Forgot to close.

**Closed by jhusain** 2016-02-05 19:21 UTC
