### ISSUE TITLE
Path returned from falcor-router is undefined after call

### ISSUE THREAD

**Issue by ekosz** [Netflix/falcor#589] opened 2015-10-24 18:06 UTC
I'm using falcor-router 0.2.9 and falcor 0.1.13

Given I have a router that looks like this:

```js
{
  route: 'my',
  get: function my() {
    const userId = this.userId;
    return Promise.resolve().then(() => {
      if (!userId) {
        return { path: ['my'], value: $atom(userId) };
      }

      return {
        path: ['my'],
        value: $ref(['usersById', userId]),
      };
    });
  },
}, {
  route: 'auth.logout',
  call: function authLogout() {
    if (!this.userId) return [ { path: ['my'], invalidate: true } ];

    return oauthService.expireOldTokens(this.userId).then(() => {       
      this.res.clearCookie('authToken');
      return [
        { path: ['my'], invalidate: true },
      ];
    });
  },
}
```

When I run

```js
model.call('auth.logout')
```

I get the error

```
TypeError: Cannot read property 'length' of undefined
    at walkPath (node_modules/falcor/lib/get/walkPath.js:17:56)
    at innerGet (node_modules/falcor/lib/get/get.js:55:13)
    at checkCacheAndReport (node_modules/falcor/lib/response/get/checkCacheAndReport.js:28:19)
    at Observable._subscribe (node_modules/falcor/lib/response/get/GetResponse.js:60:19)
    at Observable.subscribe (node_modules/falcor/lib/response/ModelResponse.js:144:29)
```

I'm still trying to get my head around `call` statements and I'm struggling a bit. I have another route `auth.login` that is working just fine, I don't know why this one is failing the way it does.

**Comment by jhusain** [comment] 2015-10-25 14:59
Like it may be expecting an arguments array as a second parameter. We should change things to make this optional. For now try passing an empty array as the next parameter.

**Comment by ekosz** [comment] 2015-10-25 17:41
@jhusain I tried that, no luck. Looking at where the code is failing it looks like:

```js
// If there is not a value in the current cache position or its a
// value type, then we are at the end of the getWalk.
if ((!curr || curr && curr.$type) || depth === path.length) {
```

Where `path` is the 4th argument to the `walkPath` method.

**Comment by sdesai** [comment] 2015-10-30 21:33
I believe this is the same issue mentioned here:
https://github.com/Netflix/falcor/issues/477#issuecomment-152336762

Your envelope coming back (if you look at the network tab) probably looks something like:

```
{
   jsonGraph: {}
   paths: [],
   invalidated: [ ['my'] ]
}
```

Which falcor is not currently handling properly. Could you verify that?

I'm about to issue a PR with a fix, if it's that same case. Thanks.

**Comment by ekosz** [comment] 2015-10-30 21:48
Actually I changed my router so that it looks like:

```js
{
  route: 'auth.logout',
  call: function authLogout() {
    if (!this.userId) return [ { path: ['my'], invalidate: true } ];

    return oauthService.expireOldTokens(this.userId).then(() => {
      this.res.clearCookie('authToken');

      return [
        { path: ['auth', 'logout'], value: $ref(['usersById', this.userId]) },
        { path: ['my'], invalidate: true },
      ];
    });
  },
}
```

So that the envelope looks like

```json
{
  "jsonGraph":{
    "auth":{"logout":{"$type":"ref","value":["usersById","7738b9c6-7f37-11e5-bc24-ff76cd8a5469"]}}
  },
  "paths":[["auth","logout"]],
  "invalidated":[["my"]]
} 
```

But I am still receiving the same error.

**Comment by sdesai** [comment] 2015-10-30 22:05
I can try out that use case also (it maybe another flavor of the bug, maybe related to the ref). The repro I'm working, mentioned on the thread I reference, didn't have the issue when a PathValue was returned along with the invalidation. Along the lines of the thread I reference - if you can get me something to debug - either the repo you're working on, or a standalone failing test, it'll go a little quicker.

Just to sync up on the original issue though, was the response the same in that case?

**Comment by sdesai** [comment] 2015-11-02 23:22
Hey @ekosz 

I tried repro'ing your use case, with this [router](https://gist.github.com/sdesai/5dce63ef8bd5ec3a7ff8) (based on your snippets in this thread) and the call seems to work fine, with the latest falcor (0.1.14) and latest falcor-router (0.2.11).

The following client code:
```
model.call("auth.logout").
                subscribe(
                    function(next) {
                        console.log(next);
                    },
                    function(error) {
                        console.log(error);
                    },
                    function() {
                        console.log("Complete");
                    }
                );
```
Results in this Envelope:
```
{
    "jsonGraph":{"auth":{"logout":{"$type":"ref","value":["usersById",150]}}},
    "paths":[["auth","logout"]],
    "invalidated":[["my"]]
}
```
And this log on the client (with no exceptions)
```
{"json":{"auth":{"logout":["usersById",150]}}}
Complete
```

As mentioned, if you have a repo or standalone test case I can look at, I can dig into it further

**Comment by sdesai** [comment] 2015-11-02 23:23
BTW, It seemed a little odd that you're returning a "value" for your `[auth, login]` call path, because that seems to be the path to your call function also.

**Comment by khy** [comment] 2015-11-05 02:56
I can confirm the above issue. When my route looked like this
```
  {
    route: 'plannedTransactionsByGuid.add',
    call: (pathSet, args) => {
      return httpPost('/plannedTransactions', args[0]).then ( plannedTransaction => {
        return [
          { path: ['plannedTransactions'], invalidate: true}
        ]
      })
    }
  }
```
I would get a `TypeError: path is undefined` (in Firefox), on this conditional
```
	    // If there is not a value in the current cache position or its a
	    // value type, then we are at the end of the getWalk.
	    if ((!curr || curr && curr.$type) || depth === path.length) {
	        onValueType(model, curr, path, depth, seed, outerResults,
	                requestedPath, optimizedPath, optimizedLength,
	                isJSONG, fromReference);
	        return;
	    }
```
However adding any regular path to my route response fixes the problem, e.g.
```
{
  route: 'plannedTransactionsByGuid.add',
  call: (pathSet, args) => {
    return httpPost('/plannedTransactions', args[0]).then ( plannedTransaction => {
      return [
        { path: ['plannedTransactionsByGuid', 'latestGuid'], value: plannedTransaction.guid },
        { path: ['plannedTransactions'], invalidate: true }
      ]
    })
  }
}
```
Not sure if this is the correct way of doing things at all since this issue, and the one linked above, are the only examples I've been able to find of what a `call` route is supposed to look like in falcor-router!

**Comment by sdesai** [comment] 2015-11-05 03:17
@khy - Yep, that original use case should be valid, and is fixed in the latest 0.x branch (#600) [ and latest dist pushed to github.netflix.io/falcor/build/falcor.browser.js.

I'll publish it to npm, once we have a few more fixes in.

I'm going to close this issue out for now, given my inability to repro as mentioned above, with the latest code base and fixes.

@ekosz - Feel free to re-open with additional repro info as mentioned, if required.

**Closed by sdesai** 2015-11-05 03:17 UTC
Labels: bug

**Comment by real34** [comment] 2015-11-30 18:22
@sdesai Have you been able to push it on npm? Otherwise, which version would you recommend to add to my dependencies to have a somewhat stable version with this bugfix?

**Comment by sdesai** [comment] 2015-11-30 22:23
Hey @real34 - we haven't pushed an update to npm 0.1.x yet.

There are a couple of fixes I'd like to get in (sitting on the 0.x-wip branch), which are just waiting on me filling out some unit tests. I can publish end of week. If you need the fixes before end of week, you can reference SHA #de5dd38d0bf458e1b9b06218915c28364d4ab4bb off the 0.x branch in your package.json if you want to pickup the 2 fixes on 0.x which aren't on npm yet.

**Comment by sdesai** [comment] 2015-12-15 20:49
@real34 

The fix to handle calls without any return Paths/Values (only invalidations), should now be on npm:
https://github.com/Netflix/falcor/blob/v0.1.15/CHANGELOG.md

This should address:
https://github.com/Netflix/falcor/issues/477
https://github.com/Netflix/falcor/issues/589#issue-113175148
https://github.com/Netflix/falcor/issues/589#issuecomment-153939508

**Comment by real34** [comment] 2016-01-11 08:40
Thanks, awesome!
