### ISSUE TITLE
not using reference routes for function calls

### ISSUE THREAD

**Issue by rnicholus** [Netflix/falcor#585] opened 2015-10-23 14:38 UTC
I'm using Falcor 0.1.13, falcor-http-datasource 0.1.2, falcor-router 0.2.9, and falcor-express 0.1.2. In other words, the latest versions at this time.

Consider the following routes:

``` javascript
{
    route: 'messages[{integers:messageIndexes}]',
    get: (pathSet) => {
        return Promise.all(pathSet.messageIndexes.map(messageIndex => {
            return new Promise(resolve => {
                messages.getId(messageIndex).then(id => resolve({
                    path: ['messages', messageIndex],
                    value: $ref(['messagesById', id])
                }))
            })
        }))
    }
},

{
    route: 'messagesById[{integers:messageIds}]["text", "swap"]',
    get: (pathSet) => {
        return Promise.all(pathSet.messageIds.map(messageId => {
            return new Promise(resolve => {
                messages.getById(messageId).then(message => {
                    resolve({
                        path: ['messagesById', messageId, 'text'],
                        value: message.text
                    })
                })
            })
        }))
    },
    set: (jsonGraphArg) => {
        return messages.update(jsonGraphArg.messagesById).then(updatedMessages => {
            return Object.keys(jsonGraphArg.messagesById).map(id => {
                return {
                    path: ['messagesById', id, 'text'],
                    value: updatedMessages[id].text
                }
            })
        })
    },
    call: (pathSet) => {
        var firstId = pathSet.messageIds[0],
            secondId = pathSet.messageIds[1]

        return messages.swap(firstId, secondId).then(addResult => {
            return [
                    $pathInvalidation(['messagesById', firstId]),
                    $pathInvalidation(['messagesById', secondId])
            ]
        })
    }
},
```

The above represents routes I have defined on my node server, now, consider the following series of calls to my client-side model representation:

First, I get the number of records. Then I ask my server for the text property of all records. 

``` javascript
model.getValue(['messages', 'length'])
    .then(length => helloWorldModel.get(['messages', {from: 0, to: length-1}, 'text']))
    .then(response => /* do stuff with message records containing text props */)
```

Assuming there are 3 records, the `get` sends a GET request with the following query params to my server

``` javascript
paths:[["messages",{"from":0,"to":2},"text"]]
method:get
```

My server responds with the data and expected references:

``` json
{"jsonGraph":{"messages":{"0":{"$type":"ref","value":["messagesById","0"]},"1":{"$type":"ref","value":["messagesById","3"]},"2":{"$type":"ref","value":["messagesById","6"]}},"messagesById":{"0":{"text":"first message"},"3":{"text":"second message"},"6":{"text":"third message"}}}}
```

Note that the IDs are intentionally non-consecutive, but that is really not important here.

Great, now my client-side model knows to address any of these messages by ID. So, I attempt to edit one of the messages text properties. My client-side code is:

``` javascript
model.setValue(['messages', 1, 'text'], 'new text')
    .then(() => /* handle edit success */)
```

This results in the following POST, using the messagesById route, as expected:

``` javascript
jsonGraph:{"jsonGraph":{"messagesById":{"3":{"text":"new text"}}},"paths":[["messagesById",3,"text"]]}
method:set
```

Everything is working as expected at this point. But things start to go wrong when I attempt to call a function on this route. Suppose I want to swap the first and last messages:

``` javascript
model.call(['messages', [0, 2], 'swap'])
    .then(() => {/* handle swap success */)
```

I would expect Falcor to immediately make use of the messageById route, since it should already know how to do this. Instead, it sends the following POST request:

``` javascript
method:call
callPath:["messages",[0,2],"swap"]
arguments:[]
pathSuffixes:[]
paths:[]
```

Server-side, this hits my "messages" route, which then "redirects" to the messagesById route. Note that I have [another issue regarding invalidating paths as a result of this call](https://github.com/Netflix/falcor/issues/477#issuecomment-150476035), but that is probably not important in this particular case. 

I don't understand why Falcor isn't re-writing my path to take into account the messagesById route (which it already knows about) when I attempt to make the `call` above. This is a problem not only for this particular call, but for other calls. Suppose my call removes a record, but the record was already removed by another user. With the above behavior, the index will be sent to the server, resolved to a _new_ ID (not matching the record I see in my client), and I will have unexpectedly removed the _wrong_ record from the store. Bad news.

**Comment by jhusain** [comment] 2015-10-23 15:33
It does appear as though these paths should be optimized. However my question is this: are you attempting to call the swap function on two different items? Because that is what should happen here. It seems like, if this method is intended to swap these two indexes in the list, the swap method should be on the messages list and you should pass the two indexes to the method as arguments.

**Comment by rnicholus** [comment] 2015-10-23 15:37
>are you attempting to call the swap function on two different items

Well, the swap function requires two records in order to perform the "swap", so I'm passing the index of each record from the client, expecting Falcor to rewrite the path to target the "swap" call in my messagesById route, replacing the indexes with IDs in the process. 

I don't _really_ want to swap two items based on index, in case the model maintained on the server has changed. Instead, I just want to swap those two records. Does this make sense, or perhaps I am misunderstanding something?

**Comment by rnicholus** [comment] 2015-10-28 04:26
Is there something I can do to help get this implemented? I'm not nearly as familiar with the Falcor codebase as you (or any of the other Falcor core devs). So, if a pull request is prudent, can you give me a few tips regarding areas of the codebase that need to be updated?

**Comment by michaelbpaulson** [comment] 2015-11-19 15:37
Sorry for letting this hang around for so long.  I was on paternity leave for some portion of this.  I'll be spending most of friday performing some backlog clean up and will get to this tomorrow!  I'll either fix the issue or provide guidance. :)

**Comment by rnicholus** [comment] 2015-11-19 15:47
No rush. Congrats! :baby_bottle:

**Comment by michaelbpaulson** [comment] 2015-12-10 21:22
So sorry.  This problem should be rather easy to fix.  Life has been a bit fast and I have been trying to answer issues as fast as I can.  The bug is clearly here in [CallResponse](https://github.com/Netflix/falcor/blob/master/lib/response/CallResponse.js#L47).  The paths are not optimized.  I can fix this with a simple cache walk and using the _missing_ paths as the optimized call path.  I'll do that asap.

**Comment by trxcllnt** [comment] 2015-12-11 00:46
@rnicholus what an ingenious use of path optimization, I don't think this approach has ever occurred to me.

@michaelbpaulson looks like we'll need to build optimized missing paths, then attempt to collapse them into a single PathSet. If we can, great. I'm not sure what to do if we can't though, because unlike get/set, it's not correct to call via the un-optimized path in this case. @jhusain thoughts?

**Comment by michaelbpaulson** [comment] 2015-12-11 01:26
@trxcllnt the good news is that its only the call path that needs to be optimized and call paths are always simple paths.  So, yeah! Unless i have missed something @jhusain . 

Paths and Suffixes should never be optimized as they will based on the callPath / references from the callPath.  So thats good.

**Comment by trxcllnt** [comment] 2015-12-11 04:00
@michaelbpaulson ah, I think that's @rnicholus's point, he's trying to use a complex path as the `callPath`:
```es6
model.call(['messages', [0, 2], 'swap'])
    .then(() => {/* handle swap success */)
 ```

The ideal output of optimizing/re-collapsing this path would be:
```es6
['messagesById', [messageID1, messageID2], 'swap']
```
which would hit his call route here:
```es6
{
    route: 'messagesById[{integers:messageIds}]["text", "swap"]',
    call: (pathSet) => {
        var { messageIds } = pathSet;
        var firstId = messageIds[0];
        var secondId = messageIds[1];

        return messages.swap(firstId, secondId).then(addResult => {
            return [
                    $pathInvalidation(['messagesById', firstId]),
                    $pathInvalidation(['messagesById', secondId])
            ]
        })
    }
}
```

@rnicholus did I miss anything?

**Comment by rnicholus** [comment] 2015-12-14 04:05
Sorry all for the (very) delayed response, I was on vacation for a couple weeks.

@trxcllnt Precisely! Your last comment reflects what I am expected from Falcor.

**Comment by michaelbpaulson** [comment] 2015-12-14 17:40
yes.  This still should be an *easy* fix on both master and 0.x branch.  Its all around optimizing `callPath`.  We could add this as a bug.  

What I am worried about is that call functions should be thought of as prototype functions.  You don't use the path to the function as arguments to the function.  I am worried that this, though available, may be an abuse of the system. @jhusain thoughts?  

Overall I could be wrong in general if callPaths are only allowed to be non complex paths.  If that is the case, then this would not be allowed (which something in my head is telling me that is the case).

**Comment by ktrott** [comment] 2016-03-04 17:57
@jhusain Can you weigh in here please?

**Comment by jhusain** [comment] 2016-03-07 16:52
The callPath must be a single path, because you're not allowed to invoke multiple functions. The Router should provide a more descriptive error here. See the call method in the DataSource interface: http://netflix.github.io/falcor/documentation/datasources.html

The right solution to the problem is to call a single swap function on the list, and pass the items you want to swap as *arguments* to the function. Assuming the list is mutable (which it appears to be), you should probably make use of deref to send the absolute paths to the items rather than indices. Otherwise you might fall prey to a race condition if the list changes between the time you downloaded the items and when you swapped them.

~~~js
var listItems = 
  model.
    get("messages[0, 2].text").
      then(function(response) {
        return model.call(
          "messages.swap", 
          [
            model.deref(response.json.messages[0]),
            model.deref(response.json.messages[2]),
          ]);
        });
~~~

Now the arguments to call will be  JSON Graph references to the messages by ID.

~~~js
{
  route: "messages.swap",
  call: function(pathSet, args) {
  // args[0] = { $type: "ref", value: ["messagesById", 57] }
  // args[1] = { $type: "ref", value: ["messagesById", 92] }
    return messages.swap(args[0].value[1], args[1].value[1]).then(addResult => {
            return [
                    // invalidate entire list in cache
                    $pathInvalidation(['messages'])
            ]
        })
    }
  }
~~~

Have a look at the "Passing Dereferenced Models  to Call" section.

http://netflix.github.io/falcor/documentation/model.html

**Comment by steveorsomethin** [comment] 2017-08-08 19:31
I'm currently performing issue triage as we get ready to perform a proper release, and closing/tagging as I go.

Closing this as it looks like the thread tapered off.

**Closed by steveorsomethin** 2017-08-08 19:31 UTC
