### ISSUE TITLE
Falcor 1.x release date

### ISSUE THREAD

**Issue by almasakchabayev** [Netflix/falcor#625] opened 2015-11-20 08:26 UTC
I want to use falcor for my next project. But after seen https://github.com/Netflix/falcor/blob/master/MIGRATIONS.md#no-more-rx I wonder whether to wait a bit and start fresh with 1.x version or to start working with 0.x right now.

**Comment by mik01aj** [comment] 2015-11-27 11:07
+1, would love to know your plans!

**Comment by michaelbpaulson** [comment] 2015-12-01 14:41
@almasakchabayev The largest change is around deref.  To use Rx would be an easy bolt on.  As far as when 1.x will be released, we have no official date, but we are working as hard as we can to wrap up all the loose ends.  

note about 1.x 
------
1.x does not mean we are out of developer preview, we simply will be adhering to semver (deref interface change + Rx is not the ModelResponses prototype).

**Comment by michaelbpaulson** [comment] 2015-12-01 14:41
I'll update this ticket once we know more (should be soon).

**Comment by jameswomack** [comment] 2015-12-05 20:16
@michaelbpaulson Thanks for updating us. Much of the tooling for modules is centered around adherence to semver. What was the reason an alternate path was taken for versioning?

**Comment by michaelbpaulson** [comment] 2015-12-05 20:50
@jameswomack We have adhered to semver since the beginning.  All additive changes to the API surface area has resulted in a minor rev.  The problem is that we don't want `1.*` to signify that we are out of _developer preview_.  So that is why I made the note about semver.  We simply changed `deref` and `ModelResponse`s prototype therefore we will be going to 1.x

**Comment by greim** [comment] 2015-12-06 06:56
Semver spec says "major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable. Version 1.0.0 defines the public API." So arguably semver doesn't require jumping to 1.0 for those breaking changes, and in fact jumping to 1.0 while still in developer preview seems like it might send a mixed signal?

**Comment by michaelbpaulson** [comment] 2015-12-06 20:51
The API is _pretty much_* is solidified.  But we are not ready to come out of developer preview mode. 

\* don't hold me do to this.

**Comment by greim** [comment] 2015-12-06 22:33
Ah, okay, thanks for the clarification.

**Comment by michaelbpaulson** [comment] 2016-01-15 15:16
We are still planning on releasing this soon.  We just have some documentation items that need to be addressed before we go out live (like its 95'). So we will be releasing soon*

So there will be no date until our tasks are finished, but soon.

\* - Soon is a relative term.  As soon as the documentation is done, we circle back around as a team, ensure that our change log / migration guide is correct, dish our some high fives, maybe some fist bumps, then we will release 1.x.

**Closed by michaelbpaulson** 2016-01-15 15:16 UTC

**Comment by almasakchabayev** [comment] 2016-01-15 17:41
Is it safe to work with a master branch?

**Comment by greim** [comment] 2016-01-15 18:56
Sorry to add noise to the conversation, but just wanted to say thanks to the Falcor team and Netflix for putting this out there and engaging the community. Really cool piece of tech and excited for 1.x!

**Comment by michaelbpaulson** [comment] 2016-01-15 18:58
@almasakchabayev yes.  `deref` should be stable now.  And _significantly_ easier to use and to implement with significantly less bugs :)

But master should be safe now.  We were going to release a 1.x-rc internally, so perhaps we will do this publicly (i should be able to get sign off shortly).

**Comment by almasakchabayev** [comment] 2016-01-16 03:16
@michaelbpaulson Great! Looking forward :)
