### ISSUE TITLE
Example Falcor DataSource/Model to wrap existing RESTful resources

### ISSUE THREAD

**Issue by baer** [Netflix/falcor#513] opened 2015-09-02 01:04 UTC
So I've now read all of the docs and watched the keynote + the 8 getting started videos and I'm still not that clear on how Falcor orchestrates data fetching. Furthermore since very few of us are lucky enough to work in greenfield projects I'd imagine a very common use case would be to start by wrapping an existing RESTful API. There are two specific scenariaos that I'm not sure about how to deal with:

---

* What would be the preferred way to expose the GET lists vs. GET details pattern. These two models effectively nested.

`GET /users`
```json
[{
  "id": "123",
  "givenName": "Brandon",
  "surame": "Pricher"
}, {
  ...
}]
```

`GET /users/123`
```json
{
    "id": "123",
    "givenName": "Brandon",
    "surame": "Pricher",
    "customerLifetimeValue": "909869.00",
    "preferredLocale": "en-US",
}
```

---

* To extend the above, lets say my view needs the Customer + the customer's address. Lets assume we have a user model but the address is an external lookup (USPS address validation for example). On the client sideI might deal with this as follows in the controller but the model seems to have some of this information already encoded in it. Furthermore, if a Falcor client doesn't request address, there is no reason to make that call. Does Falcor orchestrate dependent queries or is there a proper way to handle this?

```js
getCustomerViewModel(id) {
  let customer = getCustomer(id)
  let address = customer.then(getCustomerAddress)

  return Promise.all(customer, address)
    .then((customer, address) => {
      return customer.address = address;
    }).catch(errorHandler)
}
```

This is what the view actually needs to render the page
```json
{
    "id": "123",
    "givenName": "Brandon",
    "surame": "Pricher",
    "customerLifetimeValue": "909869.00",
    "preferredLocale": "en-US",
    "address": {
      "street": 123,
      "city": "Memphis",
      "zip": "38120-0098" 
    }
}
```

**Comment by dallonf** [comment] 2015-09-05 16:23
The latter example you gave (with address as an external resource) is actually fairly well documented and represented by the Router examples, so I'll stick with talking about what I've found regarding REST APIs, which is much less clear.

Quick warning, I will be (ab)using ES2015 and beyond syntax in this example, particularly [async/await](https://github.com/lukehoban/ecmascript-asyncawait), [arrow functions](https://babeljs.io/docs/learn-es2015/#arrows-and-lexical-this), and [enhanced object literals](https://babeljs.io/docs/learn-es2015/#enhanced-object-literals).

Also, while this particular code is untested, it's based on some of my early experiments wrapping a REST API with a Falcor Router.

Alright, enough rambling, let's code!

## Code

A naive approach is to build out a Router something like this:

```js
[{
  route: 'customers.length',
  async get(pathSet) {
    var customers = await request.get('/customers');
    return {
      path: ['customers', 'length'],
      value: customers.length
    };
  }
}, {
  route: 'customers[{integers:indices}]',
  async get(pathSet) {
    var customers = await request.get('/customers');
    return pathSet.indices.map(index => ({
      path: ['customers', index],
      // NOTE: This will actually throw errors if you request out-of-bounds indexes,
      // but for the purposes of demonstration I'll keep it concise
      value: { $type: 'ref', value: ['customersById', customers[index].id] }
    }));
  }
}, {
  route: 'customersById[{keys:ids}]["id", "givenName", "surname", "customerLifetimeValue", "preferredLocale"]',
  async get(pathSet) {
    var attributes = pathSet[2];
    // Using lodash for conciseness
    return _.flatten(await Promise.all(
      pathSet.keys.map(pathSet.ids, async id => {
        var customer = await request.get('/customers/' + id);
        return attributes.map(attribute => ({
          path: ['customersById', id, attribute],
          value: customer[attribute]
        }));
      });
    ));
  }
}]
```

This will produce pretty much exactly the results you'd want. Let's say you want to fetch some data for the first three customers, as well as the total number of customers so you know whether you should show pagination UI:

```
// On the client
model.get([
  'customers[0..2]["id", "givenName", "surname", "customerLifetimeValue"]',
  'customers.length'
]);
// Async callback elided for brevity
```

But now let's look at what kind of requests the server is making:

* `GET /customers`
* `GET /customers`
* `GET /customers/123`
* `GET /customers/456`
* `GET /customers/789`

This is very wasteful! All the data we needed was available in one `GET /customers` call. What we need to do is cache the results of that call temporarily so that the `customersById` route and the `length` route can skip their queries if the data is already available.

The official examples suggest `new`ing up a Router instance for every request to the Falcor endpoint, so that's a decent place for our short-lived cache, especially since the Router instance is exposed as `this` in the router methods. Let's see what we can do...

```
[{
  route: 'customers.length',
  async get(pathSet) {
    // Begin new code:
    var customers = this.customersListCache;
    if (!customers) {
      customers = await request.get('/customers');
      this.customersListCache = customers;
    }
    // End new code
    return {
      path: ['customers', 'length'],
      value: customers.length
    };
  }
}, {
  route: 'customers[{integers:indices}]',
  async get(pathSet) {
    // Begin new code:
    var customers = this.customersListCache;
    if (!customers) {
      customers = await request.get('/customers');
      this.customersListCache = customers;
      if (!this.customerCache) {
        this.customerCache = {};
      }
      customers.forEach(customer => {
        this.customerCache[customer.id] = customer;
      });
    }
    // End new code
    return pathSet.indices.map(index => ({
      path: ['customers', index],
      value: { $type: 'ref', value: ['customersById', customers[index].id] }
    }));
  }
}, {
  route: 'customersById[{keys:ids}]["id", "givenName", "surname", "customerLifetimeValue", "preferredLocale"]',
  async get(pathSet) {
    var attributes = pathSet[2];
    return _.flatten(await Promise.all(
      pathSet.keys.map(pathSet.ids, async id => {
        // Begin new code:
        var customer = this.customerCache && this.customerCache[id];
        if (!customer) {
          customer = await request.get('/customers/' + id);
          if (!this.customerCache) {
            this.customerCache = {};
          }
          this.customerCache[id] = customer;
        }
        // End new code
        return attributes.map(attribute => ({
          path: ['customersById', id, attribute],
          value: customer[attribute]
        }));
      });
    ));
  }
}]
```

Perfect! Now let's see what's happening on the server...

* `GET /customers`
* `GET /customers`

Well, it's certainly saved us those detail requests, but it's still requesting the list twice. This is because Falcor optimizes for maximum parallelism, and it's actually trying to resolve the `customers.length` route and the `customers[{integers:indices}]` route at the same time. Of course, we only put the value in the cache _after_ it's loaded, so that doesn't stop us from requesting it twice.

Fortunately, since we're using promises and `async`/`await`, this isn't as terrible to fix as it could be; we just need to move some code around and cache the _promises_ instead of the result:

```
[{
  route: 'customers.length',
  async get(pathSet) {
    var customersRequest = this.customersListCache;
    if (!customers) {
      customersRequest = request.get('/customers'); // Remove "await"
      this.customersListCache = customersRequest;
    }
    var customers = await customersRequest; // And put it here
    return {
      path: ['customers', 'length'],
      value: customers.length
    };
  }
}, {
  route: 'customers[{integers:indices}]',
  async get(pathSet) {
    var customersRequest = this.customersListCache;
    if (!customers) {
      customersRequest = request.get('/customers'); // Remove "await"
      this.customersListCache = customersRequest;
      if (!this.customerCache) {
        this.customerCache = {};
      }
      var customers = await customersRequest; // And put it here
      customers.forEach(customer => {
        this.customerCache[customer.id] = Promise.resolve(customer); // Wrap this in a Promise
      });
    }
    return pathSet.indices.map(index => ({
      path: ['customers', index],
      value: { $type: 'ref', value: ['customersById', customers[index].id] }
    }));
  }
}, {
  route: 'customersById[{keys:ids}]["id", "givenName", "surname", "customerLifetimeValue", "preferredLocale"]',
  async get(pathSet) {
    var attributes = pathSet[2];
    return _.flatten(await Promise.all(
      pathSet.keys.map(pathSet.ids, async id => {
        var customerRequest = this.customerCache && this.customerCache[id];
        if (!customerRequest) {
          customerRequest = request.get('/customers/' + id); // Remove await
          if (!this.customerCache) {
            this.customerCache = {};
          }
          this.customerCache[id] = customerRequest;
        }
        var customer = await customerRequest; // And put it here
        return attributes.map(attribute => ({
          path: ['customersById', id, attribute],
          value: customer[attribute]
        }));
      });
    ));
  }
}]
```

(Seriously, if you're not using `async`/`await`, you should be. I would not look forward to _that_ kind of refactoring with callbacks!)

And now on the server, it will only request `GET /customers` and return all the data you asked for.

## Conclusion

Well, we managed to wrap a very simple REST API and it makes the minimum number of requests necessary to fulfill our query. But there's certainly room for improvement. That's a lot of boilerplate code to do something very common, and I can't shake the feeling that I'm reinventing the wheel - the hard part here is arguably caching and batching, and that's what Falcor is already good at - at least on the client.

I think an ideal workflow here would involve a Falcor Model constructed on the server for each request. Each route would not only return its own data, but add _all_ the data it found to its proper place on the Model so it wouldn't be requested again. In a Router like that, I would only need to write something like this:

```
[{
  // Support multiple routes for a single getter
  routes: [
    'customers.length',
    'customers[{integers:indices}]'
  ],
  async get(pathSet) {
    var customers = await request.get('/customers');
    // Instead of returning PathValues, return the entire subset of the Graph we found
    var customersById = {};
    customers.forEach(customer => {
      customersById[id] = customer;
    });
    return {
      customers: customers.map(customer => ({
        $type: 'ref',
        path: ['customersById', customer.id]
      })),
      customersById
    };
  }
}, {
  route: 'customersById[{keys:ids}]["id", "givenName", "surname", "customerLifetimeValue", "preferredLocale"]',
  async get(pathSet) {
    var customersById = {};
    await Promise.all(pathSet.ids.map(async id => {
      var customer = await request.get('/customer/' + id);
      customersById[id] = customer;
    }));
    return {
      customersById
    }
  }
}]
```

There's a lot of implicitness here, though, and that does seem to go against some of Falcor's design principles of explicitly declaring the data you want to provide.

**Comment by MarkHerhold** [comment] 2015-09-05 18:39
@dallonf many thanks for this! It has cleared so much up for me! :+1: :+1: :+1: 

---------

I still have some fundamental concerns (as others do I am sure) that maybe you could help me clear up.

Falcor seems to be defining a new JSON API **specification**, (specifically a flavor of [HATEOAS](https://spring.io/understanding/HATEOAS)) for REST between the client and server. I am unnerved by the implications this has on existing "standards" (or ones competing to be standards) like [the JSON:API](http://jsonapi.org/), [JOSN-HAL](http://stateless.co/hal_specification.html), [JSON-LD](http://json-ld.org/), or simply "traditional" object mapping to/from JSON. Your example covers the client side case showing that you don't need to rewrite your REST server (yay), but there is so much boilerplate that servers should arguably just dedicate an entire set of endpoints or a dedicated router to serving up Falcor-spec routes. I am concerned about the additional workload and lock-in that this will cause and how other clients will be supported (e.g. Java, C#/.Net, etc, etc).

Caching and graphs are really nice, but I am having trouble seeing the cost-benefit given the risk (when is the *next* Falcor going to appear?). Maybe these are just silly concerns or I am over estimating the work that supporting Falcor will incur.

**Comment by baer** [comment] 2015-09-11 20:30
@dallonf thank you so so so much for a very thorough and well written response. I really appreciate that.

**Comment by trxcllnt** [comment] 2015-09-11 21:40
> @MarkHerhold I am unnerved by the implications this has on existing "standards" (or ones competing to be standards) like the JSON:API, JOSN-HAL, JSON-LD, or simply "traditional" object mapping to/from JSON.

Falcor was designed to be as close to your last example as possible: the minimal-possible set of type and operation definitions that makes interacting with a JSON object on a different machine as easy as interacting with a JSON object in memory. We identified the types and operations that were necessary to solve this problem at Netflix, but have no opinion on JSON standards that apply to anything beyond that goal.

**Comment by MarkHerhold** [comment] 2015-09-11 21:43
@trxcllnt Ok, makes sense. Thank you.

**Comment by barsukov** [comment] 2015-10-28 18:31
But it looks really monsterable, do we have any other solutions to not implement so many workaround which should be done by others ?

**Comment by tivac** [comment] 2015-10-28 19:17
I've got a partial implementation of router-on-the-client talking to an existing HTTP API working, I'm actually pretty happy w/ it.

https://github.com/tivac/falcor-experiment

**Comment by baer** [comment] 2015-10-28 19:41
I'd love to see a Falcor wrapper of https://swapi.co/. It would be a great way to prove out these ideas.

**Comment by wilkerlucio** [comment] 2015-10-28 20:24
@dallonf hey, a bit off topic, but can you please tell me what you are using for the async/await on the server? When I looked for it I found this one https://github.com/yortus/asyncawait but this uses a function syntax while your example seems to use native implementation, I'm using Node 4.2, do you have a tutorial to point out? Thanks.

**Comment by dallonf** [comment] 2015-10-28 20:30
@wilkerlucio [Babel](https://babeljs.io/) for the win :smile:! Alternatively, Node 4.x natively supports generators, so something like [Bluebird.coroutine](http://bluebirdjs.com/docs/api/promise.coroutine.html) or [co](https://github.com/tj/co) can get you almost all the way there even without transpilation.

**Comment by wilkerlucio** [comment] 2015-10-28 21:53
@dallonf thanks, I was using babel on the client already and just didn't realized I was one `require("babel-core/register")` away from having on the server too, so much to refactor now.

**Comment by greim** [comment] 2015-11-06 16:34
My existing REST service returns nested resources. In order to map these into json graph, my idea was to pull them into the top level and return them, even though the client didn't ask for them. For example:

```js
model.get(['usersById', 4, 'username']);
```

that causes the router to retrieve this:

```js
// GET /users/4
{
  id: 4
  username: 'greim'
  avatar: {
    id: 5
    src: 'http://.../foo.jpg'
  }
}
```

which gets converted to:

```js
{
  usersById: {
    4: {
      username: 'greim'
      avatar: { $type: 'ref', path: ['mediaById', 5] }
    }
  }
  mediaById: {
    5: {
      src: 'http://.../foo.jpg'
    }
  }
}
```

Since the service did the heavy lifting to pull that info out of the DB, we might as well give it to the client to use later. I verified it comes across the wire to the client, but `mediaById` doesn't get cached in the model, so if I subsequently do:

```js
model.get(['usersById', 4, 'avatar', 'src']);
```

that makes another call to the service. Which would defeat the scalability wins I was hoping for. If I was designing the REST API I'd do it differently, but for now that's what I have to work with. Is there any way to tell Falcor to cache stuff that gets returned but which the client didn't ask for?

**Comment by greim** [comment] 2015-11-06 17:38
Or perhaps I'm running into this? https://github.com/Netflix/falcor/issues/296

**Comment by trxcllnt** [comment] 2015-11-07 16:25
@greim there is if the extra data is returned from a `call` operation (`get` is a little trickier, but we might be able to make it work), but only if [pr-128](https://github.com/Netflix/falcor-router/pull/128) gets merged.

**Comment by greim** [comment] 2015-11-09 01:27
Thanks @trxcllnt.

Also here's the utility I'm building to convert JSON returned from my REST API objects to JSON graph, if anyone's interested: https://github.com/greim/json-graphify

**Comment by greim** [comment] 2015-11-11 18:07
An approach that's (tentatively) working for me is to create a temporary Falcor Model instance for every request, which is then available as `this._cache` from my route handlers. Then the order of operations is:

 1. Try to pull it from the temporary model/cache.
 2. If that fails, call the REST service, otherwise goto step 5.
 3. Transform the REST result into JSON Graph and stuff it in the cache.
 4. Pull it from the cache.
 5. Return the result.

Most of the cached data is discarded without ever being used, but at least it seems to eliminate redundant REST calls.

```js
const MyRouterBase = FalcorRouter.createClass([{
  route: "users[{keys:ids}][{keys:props}]",
  get: async function(pathSet) {
    const results = [];
    for (const id of pathSet.ids) {
      for (const prop of pathSet.props) {
        const path = [ 'users', id, prop ];
        let value = await this._cache.getValue(path);
        if (value === undefined) {
          const user = await service.getUserById(id);
          const pathVals = convertUser.toPathValues(user);
          await this._cache.set(...pathVals);
          value = await this._cache.getValue(path);
        }
        results.push({ path, value });
      }
    }
    return results;
  }
}]);

export default class extends MyRouterBase {
  constructor(opts) {
    super();
    this._cache = new falcor.Model({ cache: {} });
  }
}
```

**Comment by michaelbpaulson** [comment] 2016-02-05 16:10
I am going to close this down as it appears to be answered throughly.

**Closed by michaelbpaulson** 2016-02-05 16:10 UTC

**Comment by jordanh** [comment] 2016-02-05 18:29
Sneaking this in here for the archive: my teammates and I wanted a fast way of scaffolding Falcor routes so we created `falcor-saddle`: https://github.com/ParabolInc/falcor-saddle

Consider it an experiment.

**Comment by przeor** [comment] 2016-02-20 13:58
@jordanh nice saddle ! good job

**Comment by gottfrois** [comment] 2016-08-18 15:11
Thanks for the great posts here guys, really helped me to get started with my REST API integration. Specially @greim and @dallonf.

LT; DR We can't cache request promises for the `customers.length` and `customers[{integers:indices}]` routes when dealing with paginated REST APIs.

Correct me if i'm wrong @dallonf but caching the request promises only work if the http query are identical. If you have paginated API endpoints you can't cache the promise between the `customers.length` and `customers[{integers:indices}]` route.

For example, let's say your `GET /customers` endpoint returns 50 results per page. Most of REST API would also return the total number of customers in the request header or some metadata node. An implementation of such paginated customer list would look like this:

```js
[
  {
    route: "customers.length",
    get: async(function(pathSet) {
      // we don't care how much customers we return here since we only care
      // about the total number of customers given in the headers.
      var response = await(request.get('/customers', { offset: 0, limit: 50 }));
      var headers  = response.headers;

      return {
        path: ['customers', 'lenght'],
        value: headers['x-total-customers']
      };
    })
  },
  {
    route: "customers[{integers:indices}]",
    get: async(function(pathSet) {
      var offset    = pathSet.indices[0];
      var limit     = pathSet.indices.length;
      var response  = await(request.get('/customers', { offset: offset, limit: limit }));
      var customers = response.data;

      return pathSet.indices.map((idx) => {
        return {
          path: ['customers', idx],
          value: { $type: 'ref', value: ['customersById', customers[idx].id] }
        };
      });
    })
  }
]
```

Now the issue starts when we add promise caching and client request the following data:

```js
model.get(
  ['customers', 'length'],
  ['customers', { from: 50, to: 99 }]
)
```

1. Falcor execute first the `customers.length` route
2. We cache the http request promise server side
3. Falcor execute the `customers[{integers:indices}]` route using the cached promise

But since the cached promise was `request.get('/customers', { offset: 0, limit: 50 })`, it will return segments 0 to 50 and not 50 to 99 like it should.

My conclusion is that we can only cache request promises if they share the same parameters and in the case of the `length` we can't avoid the extra http query.

Do you guys have any idea how this could be avoided and still perform only 1 http query?

**Comment by greim** [comment] 2016-08-18 18:34
I faced this exact issue and  abandoned any thought of performing a single query, because in addition to the reasons you already mentioned, there are zero guarantees the two routes would ever fire simultaneously and/or in a specific order. The best you can hope is to make the `length` call as cheap as possible.

Ideally you'd have a separate REST endpoint which is cheap to call to get the `length` value.

```
/customers?... => { customers: [ ... ] }
/customers/total => { total: 1234 }
```

Less ideally, send offset/limit === 0/0 for fetching the length, in order to not uselessly spam your database with reads and cram all those bits over the wire.

**Comment by gottfrois** [comment] 2016-08-19 10:31
Thanks for the quick answer @greim. 

> Less ideally, send offset/limit === 0/0 for fetching the length, in order to not uselessly spam your database with reads and cram all those bits over the wire.

Yes this is the pass I choosed to follow.
