### ISSUE TITLE
{ranges} routes can't handle big ranges

### ISSUE THREAD

**Issue by wilkerlucio** [Netflix/falcor#594] opened 2015-10-26 16:30 UTC
I was trying here to create a route to fetch items based on time, the route looks like this `userById[{keys:ids}].mealsByTime[{ranges:timeRanges}]`.

But when I was trying to use it, I realized that when I try real timestamp numbers, for example `{from: 1445482800000, to: 1445569200000}` it hangs and never returns, it works fine with small values like `{from: 0, to: 100}`. On my understanding I was expecting the range to be processed as a single unit (as a range itself) but as I tested performance it seems that something else is going on, in a test suite that I was running, comparing the fetching using different values (please just compare the differences, the initial overhead is my test setup time):

```
{from: 0, to: 10} - 167ms
{from: 0, to: 100} - 177ms
{from: 0, to: 1000} - 177ms
{from: 0, to: 10000} - 250ms
{from: 0, to: 100000} - 820ms
{from: 0, to: 1000000} - * times out after 2s *
```

This makes the {ranges} unusable for the case that I was thinking about the timestamping for defining the dates.

There is another approach to do the same? I need to be able to be able to query items based on a time attribute.

Thanks.

**Comment by trxcllnt** [comment] 2015-10-26 23:58
@wilkerlucio just curious, are you seeing the timeout using the falcor-router in node on the server, or in the client?

Regardless, ranges probably isn't the appropriate way to represent these sorts of queries. Ranges was meant as a way to condense integer index requests for lists. The JSON Graph walk parses ranges the same way it would parse the equivalent list of contiguous integer keys (`{ to: 5 }` same as `[0, 1, 2, 3, 4, 5]`).

I'd represent your path as `userById[{keys:ids}].mealsByTime[{keys:timeRanges}]`, and always call it with `[fromTimeStamp, toTimeStamp]` as the last keys. In your route, you can fail if the route doesn't receive at least two keys.

**Comment by wilkerlucio** [comment] 2015-10-27 01:06
@trxcllnt the timeout is in my test runner (Mocha), nothing related to falcor, the point there was just to say it's unusable in way I was trying to.

Thank you very much for the suggestion, I think that should solve my issue.

**Comment by wilkerlucio** [comment] 2015-10-28 04:15
@trxcllnt I've found an issue with this approach, yesterday I did implement on the server and tested with some automatic testing, it was looking fine, but today as I tried to use on my front-end some surprise happened.

It seems the local Falcor doens't care about the keys that I expose expec the ones that I explicitally place on the query as keys, so, for instance, given this query:

```json
[["userById","abc123","mealsByTime",[1445914800000,1446001200000],["calories","description","time"]]]
```

My server responds with:

```json
{
  "jsonGraph": {
    "userById": {
      "562fb59d9365fbee31baa690": {
        "mealsByTime": {
          "1445982560000": {
            "$type": "ref",
            "value": [
              "mealById",
              "562ff181d4ac671548c83316"
            ]
          },
          "1445914800000": {
            "calories": {
              "$type": "atom"
            },
            "description": {
              "$type": "atom"
            },
            "time": {
              "$type": "atom"
            }
          },
          "1446001200000": {
            "calories": {
              "$type": "atom"
            },
            "description": {
              "$type": "atom"
            },
            "time": {
              "$type": "atom"
            }
          }
        }
      }
    },
    "mealById": {
      "562ff181d4ac671548c83316": {
        "calories": 300,
        "description": "late",
        "time": "Tue Oct 27 2015 18:49:20 GMT-0300 (BRT)"
      }
    }
  }
}
```

And finally on my client:

```javascript
model
  .get(query)
  .then(function (res) {
    console.log(res); // returns undefined
    console.log(model.getCache()); // checking cache state
  });
```

When I check my cache after this, it's like this:

```json
{
  "userById": {
    "562fb59d9365fbee31baa690": {
      "mealsByTime": {
        "1446004653000": {
          "$type": "ref",
          "value": [
            "mealById",
            "563047b15e29504848c445dc"
          ]
        },
        "1446001200000": {
          "calories": {
            "$type": "atom",
            "$size": 51
          },
          "description": {
            "$type": "atom",
            "$size": 51
          },
          "time": {
            "$type": "atom",
            "$size": 51
          }
        },
        "1446087600000": {
          "calories": {
            "$type": "atom",
            "$size": 51
          },
          "description": {
            "$type": "atom",
            "$size": 51
          },
          "time": {
            "$type": "atom",
            "$size": 51
          }
        }
      }
    }
  }
}
```

So, in my cache it got the reference for the one valid entry, and keep those "ghost entries" for the ones requested by the query itself, and finally the root keys for `mealById` is missing (although it was present in the JSON response from the server).

This prevents me from being able to access the data that I returned; I'm missing something?
How can I read the data on my client given those conditions?

Thanks.

**Comment by michaelbpaulson** [comment] 2015-12-20 21:32
@wilkerlucio I relooked at your response and I see an error.  the only time to respond with a valid reference was `1445982560000` but the data requested was `[["userById","abc123","mealsByTime",[1445914800000,1446001200000],["calories","description","time"]]]` which does not contain that timestamp.  So It would not be put into the cache.  We only merge into the cache what was requested by the operation (in this case `get`).

The real question is how did you produce that extra timestamp?  Extra data will not be merged into the cache.

**Comment by mik01aj** [comment] 2016-02-04 13:26
@wilkerlucio As far as I understand, it is so by design. This was explained in https://github.com/Netflix/falcor/issues/633.

**Comment by wilkerlucio** [comment] 2016-02-04 13:31
Ok, thanks for clarification.

**Comment by michaelbpaulson** [comment] 2016-02-04 14:30
I am going to re-open this as I think there is a fix if and only if a big range is passed in and the only matchers are ranges or specific keys.  I think we will have to get a big clever (I have some ideas) about how to solve this.

**Comment by michaelbpaulson** [comment] 2016-02-04 14:31
Actually I am going to close this down and move it to Router, as its a router problem.

**Closed by michaelbpaulson** 2016-02-04 14:31 UTC
Labels: bug
